<?php
$publicKey = $block->getPublicKey();
?>
<script type="text/javascript">
  var _twisto_config = {
    public_key: '<?php echo $publicKey ?>',
    script: 'https://api.twisto.cz/v2/lib/twisto.js'
  };
  (function(e,g,a){function h(a){return function(){b._.push([a,arguments])}}var f=["check"],b=e||{},c=document.createElement(a);a=document.getElementsByTagName(a)[0];b._=[];for(var d=0;d<f.length;d++)b[f[d]]=h(f[d]);this[g]=b;c.type="text/javascript";c.async=!0;c.src=e.script;a.parentNode.insertBefore(c,a);delete e.script}).call(window,_twisto_config,"Twisto","script");
</script>
